module MakieTutorial
```
generated by:
Pkg> generate `projectNameinLocal`
```
greet() = print("Hello World!")

greet_alien() = print("Hello ", Random.randstring(8))

#--- Builds

print(read("deps/build.jl", String))

end # module
